name: Generate Mercadona Top Up Assets

on:
  schedule:
    - cron: '0 8 * * 3'
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  generate_top_up_assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate top up assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          CCAA: madrid
          TOP_N: 5
          DAYS_WEEK: 7
        run: |
          python -m scripts.generate_assets_only

      - name: Upload outputs as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: outputs-post-top-up
          path: outputs/
          if-no-files-found: error
          retention-days: 7